fix linter issues in #345
linter checks failed due to broken link

 ERROR: 1 dead links found!
  [✖] https://github.com/cncf/cnf-wg/discussions/257 → Status: 404

link changed to:
https://github.com/lfn-cnti/bestpractices/discussions/257